project:
  type: website
  render:
    - "*.qmd"
publish:
  gh-pages: true

website:
  title: "GSM-Pharmaverse"
  site-url: https://zdz2101.github.io/PHUSE_gsm_pharmaverse
  repo-url: https://github.com/zdz2101/PHUSE_gsm_pharmaverse
  repo-branch: main
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: gsm_SDTM_example.qmd
        text: gsm & sdtm.oak
      - href: gsm_ADAM_example.qmd
        text: gsm & admiral
    right:
      - icon: github
        href: https://github.com/zdz2101/PHUSE_gsm_pharmaverse
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
